<a href="https://colab.research.google.com/github/dymiyata/advanced-programming-2025-2026/blob/main/tensor_flow_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers

tf.random.set_seed(2026)
np.random.seed(2026)
keras.utils.set_random_seed(2026)

In [13]:
### Creating Artificial Data

m = 2000

x1 = np.random.randint(-5, 5, m)
x2 = np.random.randint(-5, 5, m)
x3 = np.random.randint(-5, 5, m)

X = np.column_stack([x1, x2, x3])

score = x1**2 + x2 - 2*x3
y = (score > 8).astype(np.float32)

In [15]:
print(X[0:10,:])
print(y[0:10])

[[ 0 -1  3]
 [-4 -3 -3]
 [ 0 -1  4]
 [ 1  0 -4]
 [-1  4  0]
 [ 0  0  1]
 [-5 -3  3]
 [ 1  0  4]
 [ 1  1  0]
 [-4 -3  0]]
[0. 1. 0. 1. 0. 0. 1. 0. 0. 1.]


In [16]:
X.shape

(2000, 3)

In [17]:
y.shape

(2000,)

In [30]:
model = keras.Sequential([
    layers.Input(shape=(3,)),
    layers.Dense(4, activation="relu"),
    layers.Dense(4, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])

In [31]:
model.compile(
    optimizer="adam",
    loss="crossentropy",
    metrics=["accuracy"]
)

In [32]:
model.fit(X, y, epochs=100, verbose=False)

In [33]:
model.evaluate(X, y)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9730 - loss: 0.1054


[0.1053994745016098, 0.9729999899864197]